FROM ubuntu:19.04
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq gdal-bin vim git build-essential libsqlite3-dev \
	    zlib1g-dev golang-go curl python

# Create a directory for tippecanoe sources.
RUN mkdir -p /tmp/tippecanoe-src
RUN git clone https://github.com/mapbox/tippecanoe.git /tmp/tippecanoe-src

# Build tippecanoe.
WORKDIR /tmp/tippecanoe-src
RUN make && make install
WORKDIR /

# Remove source dirs and all build tools.
RUN rm -rf /tmp/tippecanoe-src \
  && apt-get -y remove --purge build-essential && apt-get -y autoremove

# Install Rust & xsv
RUN mkdir -p /tmp/rust
WORKDIR /tmp/rust
RUN curl https://sh.rustup.rs -sSf > rustup-init.sh
RUN chmod +x rustup-init.sh
RUN ./rustup-init.sh -y
WORKDIR /
ENV PATH=/root/.cargo/bin:${PATH}
RUN cargo install xsv
RUN rm -rf /tmp/rust

# Install gcloud SDK and command line tools.
RUN curl https://sdk.cloud.google.com | bash
ENV PATH="/root/google-cloud-sdk/bin:${PATH}"

RUN gcloud config set project measurement-lab

# NOTE: the bq cli leverages the gcloud auth, however still must perform an
# authentication initialization on the first run. This initialization also
# generates an unconditional "Welcome to BigQuery!" preamble message, which
# corrupts the remaining json output. The following command attempts to list a
# fake dataset which runs through the auth initialization and welcome message.
RUN bq --headless --project_id measurement-lab ls fake-dataset &> /dev/null || :
